### ISSUE TITLE
Add nationwide case stats for certain metrics

### ISSUE THREAD

**Issue by ctcovid-admin** [ctcovid/ctcovid.github.io#23]
Add the following metrics
 - Average cases, deaths, hospitalizations, tests
 - Case per 100K compared to average Case per 100K
 - R0 compared to average R0
 - Case responsibility % (% of nationwide cases CT is responsible for)
 - Case responsibility % (last 7 days)

**Comment by danielrusso** [comment]
Feature no longer planned.
